version: '3.8'

services:
  data:
    image: extractor
    container_name: extractor-container
    volumes:
      - /home/paulo/carla/Práctica_1_IBD/json:/json
    #deploy:
    #  replicas: 3  # Garantiza la disponibilidad de los datos, si falla un nodo los demás seguirán funcionando

volumes:
  data-volume: