version: '3'

services:
  data:
    image: extractor
    volumes:
      - {ruta donde se quieran descargar los archivos}/json:/json
    deploy:
      mode: replicated
      replicas: 3  # Garantiza la disponibilidad de los datos, si falla un nodo los demás seguirán funcionando

volumes:
  data-volume:
