version: "3.6"
volumes:
  shared-workspace:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

  esdata:
    driver: local

services:
  data:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - shared-workspace:/json
    deploy:
      mode: replicated
      replicas: 3
    command: bash -c "timeout 2m python -u data_extractor.py"

  jupyterlab:
    image: ghcr.io/bigdatainf/spark-jupyter:0.0.1
    container_name: jupyterlab
    ports:
      - 8889:8888
    volumes:
      - shared-workspace:/opt/workspace    

  spark-master:
    image: ghcr.io/bigdatainf/spark-master:0.0.1
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace

  spark-worker-1:
    image: ghcr.io/bigdatainf/spark-worker:0.0.1
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 4041:4040
      - 18081:18080
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  elasticsearch:
    image: elasticsearch:8.7.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - shared-workspace:/opt/workspace