version: '3.1'

services:

  elasticsearch:
    image: elasticsearch:8.7.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  jupyter:
    image: jupyter/minimal-notebook
    ports:
      - 8884:8888
    volumes:
      - "./data:/home/jovyan/work"  # /home/jovyan/work: carpeta de trabajo predeterminada en el contenedor de Jupyter Lab.
      # en data tengo una carpeta json con los archivos json
    command: 
      - "start-notebook.sh"
      - "--NotebookApp.token="
      - "--NotebookApp.password="  # para que no me pidan login al abrir el notebook en http://localhost:8884
